# -*- coding: utf-8 -*-
"""1BD1 (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZwqQFyVnBwPdprIC-4OOSQcPdImSSB-t
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time
import shap
import pickle
import os
import json
import re
import graphviz
from sklearn.model_selection import train_test_split, StratifiedKFold, cross_val_score, GridSearchCV
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
from sklearn.metrics import accuracy_score, precision_score, make_scorer, recall_score, f1_score, confusion_matrix, classification_report, roc_auc_score, balanced_accuracy_score
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import MinMaxScaler
from sklearn.feature_selection import RFE
from imblearn.metrics import geometric_mean_score
from sklearn.preprocessing import StandardScaler
from imblearn.pipeline import Pipeline
from sklearn.preprocessing import label_binarize
from scipy.stats import gmean
from sklearn.tree import DecisionTreeClassifier
from sklearn.multiclass import OneVsRestClassifier
from sklearn.utils.validation import check_is_fitted
from scipy.spatial.distance import cosine
from scipy.stats import spearmanr
from collections import Counter
from sklearn.tree import plot_tree, export_text, _tree
from IPython.display import display, SVG, Image
from IPython.display import Image as IPImage
from PIL import Image

# =============================================================================
# PARTE 1: CONFIGURACIÓN GENERAL PARA BD1
# =============================================================================

# Configuración de carga
data = pd.read_csv("3.data_edu2.csv", sep=';')

# Configuración de variables
target_column = 'Target'
columns_to_drop = []
apply_manual_mapping = True
apply_name_changes = False

# Mapeo manual (si aplica)
if apply_manual_mapping:
    manual_mapping = {
        "Dropout": 0,
        "Graduate": 1,
        "Enrolled": 2,
    }

# Cambios de nombres (si aplica)
if apply_name_changes:
    cambios_nombres = {
        # BD1 no necesita cambios de nombres
    }
print("== SHAPE INICIAL ==")
print(data.shape)
print(f"\nValores nulos: {data.isnull().sum().sum()}")
print()

# =============================================================================
# PARTE 2: PREPROCESAMIENTO -SEPARACIÓN DE VARIABLES-ESCALADO
# =============================================================================

# --- 1. Limpieza de Nombres de Columnas ---
data.columns = data.columns.str.strip()

print(f"Columna objetivo '{target_column}' presente: {target_column in data.columns}")

# --- 2. Procesamiento de la Variable Objetivo ---
if apply_manual_mapping:
    # Guardar valores originales para el reporte
    original_values = data[target_column].copy()

    # Aplicar mapeo manual
    data[target_column] = data[target_column].map(manual_mapping)
    # Crear target_classes ordenado por valor numérico
    target_classes = [k for k, v in sorted(manual_mapping.items(), key=lambda item: item[1])]
    target_map = manual_mapping
    Y = data[target_column]

    print("\n--- Conteo de Clases y Mapeo ---")
    print("Clases originales y conteo (ordenadas ascendentemente):")

    # Crear conteo ordenado manualmente
    counts_dict = {}
    for class_name, numeric_value in sorted(manual_mapping.items(), key=lambda x: x[1]):
        count = (original_values == class_name).sum()
        counts_dict[class_name] = count

    counts_series = pd.Series(counts_dict)
    print(counts_series.to_markdown(numalign="left", stralign="left"))

else:
    # Codificación automática con factorize
    data['Target_Encoded'], target_classes = pd.factorize(data[target_column])
    target_map = {name: i for i, name in enumerate(target_classes)}
    Y = data['Target_Encoded']

    print("\n--- Conteo de Clases y Mapeo ---")
    print("Clases originales y conteo:")
    print(data[target_column].value_counts().sort_index().to_markdown(numalign="left", stralign="left"))

print("\nMapeo de Codificación (Clase: Valor Numérico):")
print(target_map)

# --- 3. Separación de Variables (Features X y Target Y) ---
if apply_manual_mapping:
    X = data.drop(columns=[target_column] + columns_to_drop)
else:
    X = data.drop(columns=[target_column, 'Target_Encoded'] + columns_to_drop)

# --- 4. Cambio de Nombres de Columnas (OPCIONAL) ---
if apply_name_changes:
    X.columns = X.columns.to_series().replace(cambios_nombres)

# --- 5. Escalado de Features ---
scaler = MinMaxScaler()
X_scaled_array = scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled_array, columns=X.columns, index=X.index)

feature_names = X.columns.tolist()
class_names = target_classes

print(f"\nDimensiones de X (Features): {X.shape}")
print(f"Dimensiones de Y (Target): {Y.shape}")
print(f"Número de clases: {len(target_classes)}")
print(f"Clases: {class_names}")

# =============================================================================
# PARTE 3: GRÁFICO VARIABLE OBJETIVO
# =============================================================================


# --- Distribución de la variable objetivo (GENERALIZADO PARA CUALQUIER BD MULTICLASE) ---
plt.figure(figsize=(12, 7))

# Verificamos si la columna objetivo existe en el DataFrame
if target_column in data.columns:
    # --- Mapeo inverso para obtener los nombres originales ---
    # Esto funciona tanto para mapeo manual como automático
    inverse_mapping = {v: k for k, v in target_map.items()}

    # --- Conteo de frecuencias ---
    # Usamos los valores ya codificados que están en data[target_column]
    class_counts = data[target_column].value_counts().sort_index()

    # Convertir índices numéricos a nombres de clases
    class_names_numeric = class_counts.index.tolist()
    class_names_original = [inverse_mapping[num] for num in class_names_numeric]

    # --- Definición de paleta de colores (ajustable según número de clases) ---
    PALETTE = [
        "#FF8C00", "#32CD32", "#8A2BE2", "#00BFFF",
        "#FFD700", "#DA70D6", "#40E0D0", "#FFB6C1",
        "#B0E2FF", "#7FFFD4", "#FF69B4", "#98FB98",
        "#DDA0DD", "#87CEEB", "#F0E68C", "#FFA07A"
    ]

    # Asegurar que tenemos suficientes colores para todas las clases
    n_classes = len(class_names_original)
    if n_classes > len(PALETTE):
        # Generar colores adicionales si hay más clases que colores en la paleta
        import matplotlib.colors as mcolors
        additional_colors = list(mcolors.CSS4_COLORS.values())
        PALETTE.extend(additional_colors[:n_classes - len(PALETTE)])

    bar_colors = [PALETTE[i % len(PALETTE)] for i in range(n_classes)]

    # --- Gráfico de barras ---
    bars = plt.bar(class_names_original, class_counts.values,
                   color=bar_colors, edgecolor="black")

    # --- Etiquetas y títulos ---
    plt.title(f"Distribución de la Variable Objetivo ({target_column})", fontsize=16, fontweight='bold')
    plt.xlabel(f"Categorías de {target_column}", fontsize=12)
    plt.ylabel("Número de instancias", fontsize=12)

    # Rotar etiquetas para mejor legibilidad
    rotation_angle = 45 if max(len(str(name)) for name in class_names_original) > 15 else 0
    plt.xticks(rotation=rotation_angle, ha="right" if rotation_angle > 0 else "center", fontsize=10)

    # --- Mostrar valores encima de cada barra ---
    max_height = class_counts.max()
    for bar in bars:
        yval = bar.get_height()
        plt.text(
            bar.get_x() + bar.get_width()/2.0,
            yval + (0.01 * max_height),  # Ajuste dinámico de la posición del texto
            f"{int(yval)}",
            ha='center', va='bottom', fontsize=10, fontweight='bold'
        )

    # --- Añadir información adicional en el gráfico ---
    total_instances = len(data)
    plt.text(0.82, 0.98, f'Total instancias: {total_instances}\nNúmero de clases: {n_classes}',
             transform=plt.gca().transAxes, fontsize=10, verticalalignment='top',
             bbox=dict(boxstyle='round', facecolor='wheat', alpha=0.8))

    plt.tight_layout()
    plt.show()

else:
    print(f"Error: La columna '{target_column}' no se encontró en el DataFrame.")
    print("Columnas disponibles:", data.columns.tolist())

#------------------MODELO BASE GLOBAL (GENERALIZADO)---------------------------

# =============================================================================
# PARTE 4: DIVISION TRAIN/TEST- MODELO BASE GLOBAL (GENERALIZADO)
# =============================================================================


# 1) Split (estratificado) usando X_scaled y Y
X_train, X_test, Y_train, Y_test = train_test_split(X_scaled, Y, test_size=0.3, random_state=42, stratify=Y)

# 2) Modelo base y ajuste
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(X_train, Y_train)

# 3) Predicciones
Y_pred_train = dt_model.predict(X_train)
Y_pred_test  = dt_model.predict(X_test)

# 4) Métricas (misma firma que tu base; se añaden salvaguardas)
def calculate_metrics(Y_true, Y_pred, model, X_data):
    accuracy = accuracy_score(Y_true, Y_pred)
    precision = precision_score(Y_true, Y_pred, average='weighted', zero_division=0)
    recall = recall_score(Y_true, Y_pred, average='weighted', zero_division=0)
    f1 = f1_score(Y_true, Y_pred, average='weighted', zero_division=0)
    balanced_acc = balanced_accuracy_score(Y_true, Y_pred)
    # Para AUC multiclasificación, requiere probabilidades
    auc = roc_auc_score(Y_true, model.predict_proba(X_data), multi_class='ovr', average='weighted')
    gmean = geometric_mean_score(Y_true, Y_pred, average='weighted')

    return {
        'Accuracy': accuracy,
        'Precision': precision,
        'Recall': recall,
        'F1 Score': f1,
        'Balanced Accuracy': balanced_acc,
        'AUC': auc,
        'G-mean': gmean
    }

# 5) Reporte Entrenamiento
print("\nRESULTADOS PARA EL CONJUNTO DE ENTRENAMIENTO:")
metrics_train = calculate_metrics(Y_train, Y_pred_train, dt_model, X_train)
print("\nMétricas de rendimiento:")
for metric, value in metrics_train.items():
    print(f"{metric}: {value:.4f}")

# Etiquetas dinámicas para matrices de confusión (sin suponer 1..5)
labels_sorted_train = np.sort(Y_train.unique())
conf_matrix_train = confusion_matrix(Y_train, Y_pred_train, labels=labels_sorted_train)
conf_matrix_train_df = pd.DataFrame(conf_matrix_train, index=labels_sorted_train, columns=labels_sorted_train)
print("\nMatriz de confusión (Entrenamiento):")
print(conf_matrix_train_df.to_markdown(index=True, numalign="left", stralign="left"))

print("\nInforme de clasificación (Entrenamiento):")
print(classification_report(Y_train, Y_pred_train, zero_division=0))

# 6) Reporte Prueba
print("\nRESULTADOS PARA EL CONJUNTO DE PRUEBA:")
metrics_test = calculate_metrics(Y_test, Y_pred_test, dt_model, X_test)
print("\nMétricas de rendimiento:")
for metric, value in metrics_test.items():
    print(f"{metric}: {value:.4f}")

labels_sorted_test = np.sort(Y_test.unique())
conf_matrix_test = confusion_matrix(Y_test, Y_pred_test, labels=labels_sorted_test)
conf_matrix_test_df = pd.DataFrame(conf_matrix_test, index=labels_sorted_test, columns=labels_sorted_test)
print("\nMatriz de confusión (Prueba):")
print(conf_matrix_test_df.to_markdown(index=True, numalign="left", stralign="left"))

print("\nInforme de clasificación (Prueba):")
print(classification_report(Y_test, Y_pred_test, zero_division=0))

#-----------------OPTIMIZANDO EL ÁRBOL----------------------

# =============================================================================
# PARTE 5: OPTIMIZANDO EL ÁRBOL
# =============================================================================

# 0) Modelo base para el grid
dt_model_tuned = DecisionTreeClassifier(random_state=42)

param_grid = {
    'max_depth': [5, 10, 15, None],
    'min_samples_leaf': [10, 50, 100, 200],
    'min_samples_split': [20, 100, 200],
    'criterion': ['gini', 'entropy'],
    'class_weight': ['balanced', None]
}
# 2) Configurar GridSearchCV
grid_search = GridSearchCV(
    estimator=dt_model_tuned,
    param_grid=param_grid,
    cv=5,
    n_jobs=-1,
    scoring='f1_weighted',
    verbose=2,
    refit=True  # asegura que best_estimator_ quede ajustado con todo el train
)

# 3) Entrenar GridSearchCV sobre los datos ORIGINALES (X_train, Y_train)
print("Iniciando GridSearchCV (f1_weighted, cv=5)...")
grid_search.fit(X_train, Y_train)

# 4) Resultados del grid
print("\n--- Búsqueda Completada ---")
print("Mejores hiperparámetros encontrados:")
best_params = grid_search.best_params_
print(best_params)


modelo_generalizado = DecisionTreeClassifier(random_state=42,**best_params)
modelo_generalizado.fit(X_train, Y_train)

# Función de métricas con `zero_division=1`
def calcular_metricas_formato(y_true, y_pred, y_proba, conjunto):
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, average='weighted', zero_division=1)
    recall = recall_score(y_true, y_pred, average='weighted')
    f1 = f1_score(y_true, y_pred, average='weighted')
    auc = roc_auc_score(y_true, y_proba, multi_class='ovr')
    g_mean = np.sqrt(precision * recall)

    print(f"\nMétricas de rendimiento para el conjunto {conjunto}:")
    print(f"Accuracy: {accuracy:.4f}")
    print(f"Precision: {precision:.4f}")
    print(f"Recall: {recall:.4f}")
    print(f"F1 Score: {f1:.4f}")
    print(f"AUC: {auc:.4f}")
    print(f"G-mean: {g_mean:.4f}")
    print("-" * 60)

# Generar predicciones y probabilidades
y_train_pred = modelo_generalizado.predict(X_train)
y_train_proba = modelo_generalizado.predict_proba(X_train)
y_test_pred = modelo_generalizado.predict(X_test)
y_test_proba = modelo_generalizado.predict_proba(X_test)


calcular_metricas_formato(Y_train, y_train_pred, y_train_proba, "Entrenamiento")
calcular_metricas_formato(Y_test, y_test_pred, y_test_proba, "Prueba")

#------------importancia de características-----------------

# =============================================================================
# PARTE 6: IMPORTANCIA DE CARACTERÍSTICAS
# =============================================================================

print("Extrayendo la importancia de características directamente del modelo de Árbol de Decisión...")

# 1. Obtener las importancias del modelo
importances = modelo_generalizado.feature_importances_
feature_names = X.columns  # Usamos X.columns para obtener todos los nombres de características

# 2. Crear un DataFrame para visualizar mejor los resultados
feature_importance_df = pd.DataFrame({
    'Característica': feature_names,
    'Importancia': importances
})

# 3. Ordenar el DataFrame por importancia (de mayor a menor)
feature_importance_df = feature_importance_df.sort_values(by='Importancia', ascending=False)

# 4. Mostrar las 20 características más importantes (en formato de tabla para el output)
print("\n--- TOP 20 CARACTERÍSTICAS MÁS IMPORTANTES SEGÚN EL MODELO OPTIMIZADO ---")
print(feature_importance_df.head(20).to_markdown(index=False, numalign="left", stralign="left"))

# 5. Visualizar las 10 características más importantes
print("\nGenerando gráfico de importancia de características...")
plt.figure(figsize=(12, 8))
sns.barplot(x='Importancia', y='Característica', data=feature_importance_df.head(10), palette='viridis')
plt.title('Top 10 Características más Importantes (Modelo Optimizado)', fontsize=16)  # CORREGIDO: 10 en lugar de 20
plt.xlabel('Importancia Relativa', fontsize=12)
plt.ylabel('Característica', fontsize=12)
plt.grid(axis='x', linestyle='--', alpha=0.7)
plt.tight_layout()

# Guardar la gráfica
plot_filename = 'importancia_caracteristicas_top10.png'  # NOMBRE ESTANDARIZADO
plt.savefig(plot_filename, dpi=300, bbox_inches='tight')
plt.show()  # AÑADIDO: para mostrar el gráfico
print(f"Gráfica guardada como '{plot_filename}'")

#--------------MODELO GENERALIZADO-GRAFICO ARBOL -------------------------------

# =============================================================================
# PARTE 7: MODELO GENERALIZADO - GRÁFICO ÁRBOL
# =============================================================================
class_names_ordered = [str(class_names[i]) for i in modelo_generalizado.classes_]

PALETTE = [
    "#FF8C00", "#32CD32", "#8A2BE2", "#00BFFF",
    "#FFD700", "#DA70D6", "#40E0D0", "#FFB6C1",
    "#B0E2FF", "#7FFFD4"
]
CLASS_COLORS = {cls: PALETTE[i % len(PALETTE)]
                for i, cls in enumerate(class_names_ordered)}

def _arr_str_int(a):
    a = list(map(int, a))
    return "[" + ", ".join(str(x) for x in a) + "]"

def _arr_str_float(a):
    return "[" + ", ".join(f"{float(x):.2f}" for x in a) + "]"

def visualize_full_tree_graphviz_fixed_nice(
    model,
    feature_names,
    out_filename="ARBOL_GRAPHVIZ_NICE",
    dpi=220,
    ranksep="0.55",
    nodesep="0.35",
):
    tree_ = model.tree_

    dot = graphviz.Digraph(
        comment="Árbol de Decisión (legible, márgenes amplios)",
        engine="dot",
        format="png",
        graph_attr={
            "rankdir": "TB",
            "dpi": str(dpi),
            "ranksep": ranksep,
            "nodesep": nodesep,
            "pad": "0.2",
        },
        node_attr={
            "shape": "box",
            "style": "rounded,filled",
            "fontname": "Helvetica",
            "fontsize": "11",
            "margin": "0.16,0.10",
            "penwidth": "1.4",
        },
        edge_attr={
            "fontname": "Helvetica",
            "fontsize": "9",
        },
    )

    def add_node_and_edges(nid):
        counts_w = tree_.value[nid][0].astype(float)
        total_w  = counts_w.sum()
        probs    = counts_w / total_w if total_w > 0 else np.zeros_like(counts_w)

        samples  = int(tree_.n_node_samples[nid])
        est_cnts = np.rint(probs * samples).astype(int)

        maj_idx  = int(np.argmax(probs if total_w > 0 else counts_w))
        maj_name = class_names_ordered[maj_idx]
        color    = CLASS_COLORS.get(maj_name, "#EEEEEE")

        impurity = float(tree_.impurity[nid])
        is_leaf  = (tree_.children_left[nid] == tree_.children_right[nid])

        value_str = _arr_str_int(est_cnts)
        probs_str = _arr_str_float(probs)

        if is_leaf:
            label = (
                f"samples = {samples}\n"
                f"value = {value_str}\n"
                f"probs = {probs_str}\n"
                f"class = {maj_name}"
            )
            dot.node(str(nid), label=label, fillcolor=color, shape="ellipse")
        else:
            feat = feature_names[tree_.feature[nid]]
            thr  = float(tree_.threshold[nid])
            label = (
                f"{feat} <= {thr:.3f}\n"
                f"gini = {impurity:.3f} | samples = {samples}\n"
                f"value = {value_str}\n"
                f"probs = {probs_str}\n"
                f"class = {maj_name}"
            )
            dot.node(str(nid), label=label, fillcolor="#FFFFFF", shape="box")

            left  = tree_.children_left[nid]
            right = tree_.children_right[nid]
            dot.edge(str(nid), str(left),  label="True")
            dot.edge(str(nid), str(right), label="False")
            add_node_and_edges(left)
            add_node_and_edges(right)

    add_node_and_edges(0)
    path = dot.render(out_filename, cleanup=True)
    print(f"✓ PNG guardado: {path}")
    # CAMBIO AQUÍ: Usar IPImage en lugar de Image
    display(IPImage(filename=path))

# Ejemplo de uso
visualize_full_tree_graphviz_fixed_nice(
    model=modelo_generalizado,
    feature_names=feature_names,
    out_filename="ARBOL_GENERALIZADO",
    dpi=240,
    ranksep="0.6",
    nodesep="0.4",
)

#--------------MODELO GENERALIZADO-ARBOL TEXTO -------------------------------

# =============================================================================
# PARTE 8: MODELO GENERALIZADO -  Árbol en texto + Reglas (soporte% y confianza%)
# =============================================================================

# CORRECCIÓN: Verificar el tipo de target_classes antes de convertirlo
if hasattr(target_classes, 'tolist'):
    class_names = target_classes.tolist()
else:
    class_names = target_classes  # Ya es una lista

feature_names = X.columns.tolist()

# --- Árbol interno ---
tree_          = modelo_generalizado.tree_
n_nodes        = tree_.node_count
children_left  = tree_.children_left
children_right = tree_.children_right
features_idx   = tree_.feature
thresholds     = tree_.threshold
values_raw     = tree_.value.squeeze(1)     # [n_nodes, n_classes], flotante (ponderado)
n_node_samples = tree_.n_node_samples
is_leaf        = children_left == _tree.TREE_LEAF

# --- Utilidades ---
def fmt(x, k=2):
    return f"{x:.{k}f}"

def counts_str(v_float):
    """value como conteos enteros redondeados (evita truncado a 0)."""
    v_int = np.rint(np.asarray(v_float, dtype=float)).astype(int)
    return "[" + ", ".join(str(int(x)) for x in v_int) + "]"

# ========== 1) ÁRBOL EN TEXTO — MODELO GENERALIZADO ==========
def ascii_tree_global(prec=2, idioma="es"):
    """
    Árbol en texto (tipo export_text) para TODO el modelo.
    En las hojas se imprime:
      class: <pred> (samples=N, value=[...], soporte=XX.XX%, confianza=YY.YY%)
    Donde 'confianza' es hacia la clase predicha en esa hoja.
    """
    N_total = float(len(X))
    lines = []

    def dump(u, depth):
        indent = "|   " * depth
        if is_leaf[u]:
            v = values_raw[u].astype(float)
            total_leaf = v.sum()
            pred_idx = int(v.argmax())
            conf_pct = 100.0 * (v[pred_idx] / total_leaf) if total_leaf > 0 else 0.0
            supp_pct = 100.0 * (float(n_node_samples[u]) / N_total) if N_total > 0 else 0.0

            cname = class_names[pred_idx]
            n  = int(np.rint(n_node_samples[u]))
            val = counts_str(v)

            if idioma == "es":
                lines.append(
                    f"{indent}|--- class: {cname} (samples={n}, value={val}, "
                    f"soporte={fmt(supp_pct, prec)}%, confianza={fmt(conf_pct, prec)}%)"
                )
            else:
                lines.append(
                    f"{indent}|--- class: {cname} (samples={n}, value={val}, "
                    f"support={fmt(supp_pct, prec)}%, confidence={fmt(conf_pct, prec)}%)"
                )
            return

        feat = feature_names[features_idx[u]]
        thr  = thresholds[u]
        lines.append(f"{indent}|--- {feat} <= {fmt(thr, prec)}")
        dump(children_left[u], depth+1)
        lines.append(f"{indent}|--- {feat} > {fmt(thr, prec)}")
        dump(children_right[u], depth+1)

    dump(0, 0)
    return "\n".join(lines)

# ========== 2) REGLAS (IF–THEN) GLOBALES — COMPACTAS + CSV ==========
def extract_global_rules(prec=2):
    """
    Devuelve lista de dicts con reglas IF–THEN para TODAS las hojas.
    - class: clase predicha en la hoja
    - conditions: lista de condiciones desde la raíz
    - samples, value, support_%, confidence_%, leaf_id
    """
    N_total = float(len(X))
    rules = []

    def dfs(u, conds):
        if is_leaf[u]:
            v = values_raw[u].astype(float)
            total_leaf = v.sum()
            pred_idx = int(v.argmax())
            cname = class_names[pred_idx]
            n_leaf = float(n_node_samples[u])

            conf_pct = 100.0 * (v[pred_idx] / total_leaf) if total_leaf > 0 else 0.0
            supp_pct = 100.0 * (n_leaf / N_total) if N_total > 0 else 0.0

            rules.append({
                "class": cname,
                "conditions": conds.copy(),
                "samples": int(np.rint(n_node_samples[u])),
                "value": counts_str(v),
                "support_%": float(fmt(supp_pct, prec)),
                "confidence_%": float(fmt(conf_pct, prec)),
                "leaf_id": int(u),
            })
            return

        feat = feature_names[features_idx[u]]
        thr  = thresholds[u]
        dfs(children_left[u],  conds + [f"{feat} <= {fmt(thr, prec)}"])
        dfs(children_right[u], conds + [f"{feat} > {fmt(thr, prec)}"])

    dfs(0, [])
    return rules

# --------- Ejecutar: Árbol en texto (global) ----------
print("\n" + "="*75)
print("=== Árbol en modo texto — Modelo Generalizado ===")
print("="*75)
ascii_txt_global = ascii_tree_global(prec=2, idioma="es")
print(ascii_txt_global)

with open("arbol_texto_modelo_generalizado.txt", "w", encoding="utf-8") as f:
    f.write("=== Árbol en modo texto — Modelo Generalizado ===\n\n")
    f.write(ascii_txt_global + "\n")
print("✓ Guardado: arbol_texto_modelo_generalizado.txt")

# --------- Ejecutar: Reglas globales ----------
print("\n" + "="*75)
print("=== Reglas IF-THEN — Modelo Generalizado ===")
print("="*75)
rules_global = extract_global_rules(prec=2)

# Mostrar primeras 10 reglas
print(f"\nTotal de reglas (hojas): {len(rules_global)}")
print("\n--- Primeras 10 reglas ---")
for i, rule in enumerate(rules_global[:10]):
    print(f"\nRegla {i+1}:")
    print(f"  SI {' Y '.join(rule['conditions'])}")
    print(f"  ENTONCES class = {rule['class']}")
    print(f"  (samples={rule['samples']}, value={rule['value']}, "
          f"soporte={rule['support_%']}%, confianza={rule['confidence_%']}%)")

# Guardar reglas en CSV
rules_df = pd.DataFrame(rules_global)
rules_df.to_csv("reglas_modelo_generalizado.csv", index=False, encoding="utf-8")
print(f"\n✓ Reglas guardadas: reglas_modelo_generalizado.csv ({len(rules_global)} reglas)")

#--------------MODELO GENERALIZADO-REGLAS-------------------------------

# ================================================================================================
# PARTE 9: MODELO GENERALIZADO - Árbol en texto + Reglas (soporte% y confianza%) -FORMATO COMPACTO
# ================================================================================================

# --- INICIALIZACIÓN DEL ÁRBOL (CORREGIDO) ---
# CORRECCIÓN: Usar X_scaled.columns en lugar de X.columns
feature_names = X_scaled.columns.tolist()

# CORRECCIÓN: Verificar el tipo de target_classes antes de convertirlo
if hasattr(target_classes, 'tolist'):
    class_names = target_classes.tolist()
else:
    class_names = target_classes  # Ya es una lista

# --- Árbol interno ---
tree_          = modelo_generalizado.tree_
n_nodes        = tree_.node_count
children_left  = tree_.children_left
children_right = tree_.children_right
features_idx   = tree_.feature
thresholds     = tree_.threshold
values_raw     = tree_.value.squeeze(1)     # [n_nodes, n_classes], flotante (ponderado)
n_node_samples = tree_.n_node_samples

# CORRECCIÓN: Detectar nodos hoja de manera compatible
# En scikit-learn, un nodo es hoja si children_left[i] == -1
is_leaf = (children_left == -1) & (children_right == -1)

# --- Utilidades ---
def fmt(x, k=2):
    return f"{x:.{k}f}"

def counts_str(v_float):
    """value como conteos enteros redondeados (evita truncado a 0)."""
    v_int = np.rint(np.asarray(v_float, dtype=float)).astype(int)
    return "[" + ", ".join(str(int(x)) for x in v_int) + "]"

# ========== FUNCIÓN EXTRACT_GLOBAL_RULES CORREGIDA ==========
def extract_global_rules(prec=2):
    """
    Devuelve lista de dicts con reglas IF–THEN para TODAS las hojas.
    - class: clase predicha en la hoja
    - conditions: lista de condiciones desde la raíz
    - samples, value, support_%, confidence_%, leaf_id
    """
    N_total = float(len(X_scaled))  # CORRECCIÓN: Usar X_scaled
    rules = []

    def dfs(u, conds):
        if is_leaf[u]:
            v = values_raw[u].astype(float)
            total_leaf = v.sum()
            pred_idx = int(v.argmax())
            cname = class_names[pred_idx]
            n_leaf = float(n_node_samples[u])

            conf_pct = 100.0 * (v[pred_idx] / total_leaf) if total_leaf > 0 else 0.0
            supp_pct = 100.0 * (n_leaf / N_total) if N_total > 0 else 0.0

            rules.append({
                "class": cname,
                "conditions": conds.copy(),
                "samples": int(np.rint(n_node_samples[u])),
                "value": counts_str(v),
                "support_%": float(fmt(supp_pct, prec)),
                "confidence_%": float(fmt(conf_pct, prec)),
                "leaf_id": int(u),
            })
            return

        # CORRECCIÓN: Verificar índice de característica
        feat_idx = features_idx[u]
        if feat_idx < 0 or feat_idx >= len(feature_names):
            feat_name = f"Feature_{feat_idx}"
        else:
            feat_name = feature_names[feat_idx]

        thr  = thresholds[u]
        dfs(children_left[u],  conds + [f"{feat_name} <= {fmt(thr, prec)}"])
        dfs(children_right[u], conds + [f"{feat_name} > {fmt(thr, prec)}"])

    dfs(0, [])
    return rules

# --------- Ejecutar: Reglas IF–THEN (global) ----------
print("Extrayendo reglas del árbol...")
all_rules = extract_global_rules(prec=2)

print("\n" + "="*75)
print("RESUMEN DE REGLAS — MODELO GENERALIZADO (FORMATO COMPACTO)")
print("="*75)
print(f"Total de reglas (hojas): {len(all_rules)}")

# Mostrar solo las primeras 20 reglas para no saturar la salida
print("\n--- Primeras 20 reglas (de {len(all_rules)}) ---")
for i, r in enumerate(all_rules[:20], 1):
    conds_str = " AND ".join(r["conditions"]) if r["conditions"] else "(siempre)"
    print(f"{i:3d}) IF {conds_str}")
    print(f"     THEN class = {r['class']} (soporte: {r['support_%']}%, confianza: {r['confidence_%']}%)")

# Guardar CSV con metadatos (útil para análisis/ordenaciones)
df_rules = pd.DataFrame({
    "rule_id": np.arange(1, len(all_rules)+1),
    "class": [r["class"] for r in all_rules],
    "conditions": [" AND ".join(r["conditions"]) if r["conditions"] else "" for r in all_rules],
    "samples": [r["samples"] for r in all_rules],
    "value": [r["value"] for r in all_rules],
    "support_%": [r["support_%"] for r in all_rules],
    "confidence_%": [r["confidence_%"] for r in all_rules],
    "leaf_id": [r["leaf_id"] for r in all_rules],
})
df_rules.to_csv("reglas_modelo_generalizado.csv", index=False, encoding="utf-8")
print(f"\n✓ Guardado CSV: reglas_modelo_generalizado.csv ({len(all_rules)} reglas)")

# --- ANÁLISIS ADICIONAL DE LAS REGLAS ---
print("\n" + "="*75)
print("ANÁLISIS DE REGLAS — ESTADÍSTICAS")
print("="*75)

# Distribución por clase
class_dist = df_rules['class'].value_counts()
print("\nDistribución de reglas por clase:")
for clase, count in class_dist.items():
    print(f"  {clase}: {count} reglas ({count/len(all_rules)*100:.1f}%)")

# Reglas más confiables
high_conf_rules = df_rules[df_rules['confidence_%'] > 80]
print(f"\nReglas con confianza > 80%: {len(high_conf_rules)}")

# Reglas con mejor soporte
top_support_rules = df_rules.nlargest(5, 'support_%')
print(f"\nTop 5 reglas por soporte:")
for _, rule in top_support_rules.iterrows():
    print(f"  Soporte: {rule['support_%']}% | Confianza: {rule['confidence_%']}% | Clase: {rule['class']}")

# Resumen de confianza por clase
print(f"\nConfianza promedio por clase:")
for clase in class_dist.index:
    class_rules = df_rules[df_rules['class'] == clase]
    avg_conf = class_rules['confidence_%'].mean()
    print(f"  {clase}: {avg_conf:.1f}%")

#--------------MODELO ESPECIALISTA-GRAFICO ARBOL -------------------------------

# ================================================================================================
# PARTE 10: MODELO ESPECIALISTA - GRÁFICO ÁRBOL POR CLASE
# ================================================================================================

feature_names = list(getattr(X, "columns", [f"feat_{i}" for i in range(modelo_generalizado.n_features_in_)]))
class_names   = list(class_names)

def build_palette_for_classes(class_names, palette=PALETTE):
    if len(class_names) > len(palette):
        raise ValueError(f"Se requieren ≤ {len(palette)} clases; recibidas {len(class_names)}.")
    return {cls: col for cls, col in zip(class_names, palette)}

CLASS_COLORS = build_palette_for_classes(class_names)

def _safe_name(s):
    return re.sub(r'[^A-Za-z0-9._-]+', '_', str(s))

# --------------------------------------------
# Estructura del árbol y caminos por clase
# --------------------------------------------
tree_ = modelo_generalizado.tree_
n_nodes = tree_.node_count
children_left  = tree_.children_left
children_right = tree_.children_right
is_leaf        = children_left == _tree.TREE_LEAF

value_raw = tree_.value.squeeze(1)            # [n_nodes, n_classes] (pesos)
pred_cls_idx = value_raw.argmax(axis=1)

def get_path_nodes_for_class(target_class_name: str):
    target_idx = class_names.index(target_class_name)
    has_target_desc = np.zeros(n_nodes, dtype=bool)

    def dfs(u: int) -> bool:
        if is_leaf[u]:
            has_target_desc[u] = (pred_cls_idx[u] == target_idx)
            return has_target_desc[u]
        l = dfs(children_left[u]); r = dfs(children_right[u])
        has_target_desc[u] = l or r
        return has_target_desc[u]

    dfs(0)

    path_nodes = set()
    def mark(u: int):
        if not has_target_desc[u]:
            return
        path_nodes.add(u)
        if not is_leaf[u]:
            if has_target_desc[children_left[u]]:  mark(children_left[u])
            if has_target_desc[children_right[u]]: mark(children_right[u])
    mark(0)
    return path_nodes

# ------------------------------------------------------
# Render de caminos por clase
# ------------------------------------------------------
def draw_paths_per_class_graphviz(
    model,
    feature_names,
    class_names,
    out_prefix="ARBOL_POR_CLASE_AJUSTADO_",
    dpi=220,
    node_font="Helvetica",
    edge_font="Helvetica",
):
    tree = model.tree_

    def counts_probs_for_node(u: int):
        """Devuelve (counts_int, probs) usando pesos -> probabilidades -> conteos aprox."""
        w = value_raw[u].astype(float)                 # pesos por clase
        w_sum = w.sum()
        if w_sum > 0:
            probs = w / w_sum
        else:
            probs = np.zeros_like(w, dtype=float)
        samples = int(tree.n_node_samples[u])
        counts = np.rint(probs * samples).astype(int)  # reconstrucción de conteos
        return counts, probs

    def fmt_counts(counts):
        return "[" + ", ".join(str(int(x)) for x in counts) + "]"

    def fmt_probs(probs):
        return "[" + ", ".join(f"{p:.2f}" for p in probs) + "]"

    for cls_name in class_names:
        color = CLASS_COLORS[cls_name]
        path_nodes = get_path_nodes_for_class(cls_name)
        if not path_nodes:
            print(f"(i) No hay camino para la clase: {cls_name}")
            continue

        dot = graphviz.Digraph(
            comment=f"Caminos hacia {cls_name}",
            graph_attr={
                "dpi": str(dpi),
                "rankdir": "TB",
                "splines": "true",
                "nodesep": "0.35",
                "ranksep": "0.45",
                "fontname": node_font,
            },
            node_attr={
                "shape": "box",
                "style": "filled,rounded",
                "fontname": node_font,
                "fontsize": "14",
                "penwidth": "2",
                "color": "black",
            },
            edge_attr={
                "fontname": edge_font,
                "fontsize": "12",
                "color": "black",
                "arrowsize": "0.8",
            },
        )

        def add_nodes_and_edges(u: int):
            if u not in path_nodes:
                return

            counts, probs = counts_probs_for_node(u)
            samples = int(tree.n_node_samples[u])
            gini    = float(tree.impurity[u])
            majority_cls = class_names[int(pred_cls_idx[u])]

            if is_leaf[u]:
                label = (
                    f"samples = {samples}\n"
                    f"value = {fmt_counts(counts)}\n"
                    f"probs = {fmt_probs(probs)}\n"
                    f"class = {majority_cls}"
                )
                dot.node(str(u), label=label, fillcolor=color, shape="ellipse")
            else:
                feat = feature_names[int(tree.feature[u])]
                thr  = float(tree.threshold[u])
                label = (
                    f"{feat} <= {thr:.3f}\n"
                    f"gini = {gini:.3f} | samples = {samples}\n"
                    f"value = {fmt_counts(counts)}\n"
                    f"probs = {fmt_probs(probs)}\n"
                    f"class = {majority_cls}"
                )
                dot.node(str(u), label=label, fillcolor=color, shape="box")

                lc = int(children_left[u]);  rc = int(children_right[u])
                if lc in path_nodes:
                    dot.edge(str(u), str(lc), label="True")
                    add_nodes_and_edges(lc)
                if rc in path_nodes:
                    dot.edge(str(u), str(rc), label="False")
                    add_nodes_and_edges(rc)

        add_nodes_and_edges(0)

        out_name = f"{out_prefix}{_safe_name(cls_name)}"
        dot.render(out_name, format="png", cleanup=True)
        print(f"✓ Guardado: {out_name}.png")
        # CORRECCIÓN CRÍTICA: Usar IPImage en lugar de Image
        display(IPImage(filename=f"{out_name}.png"))

# -----------------------------
# Ejecutar
# -----------------------------
draw_paths_per_class_graphviz(
    model=modelo_generalizado,
    feature_names=feature_names,
    class_names=class_names,
    out_prefix="ARBOL_POR_CLASE_",
    dpi=220,
    node_font="Helvetica",
    edge_font="Helvetica",
)

#--------------MODELO ESPECIALISTA-ARBOL TEXTO -------------------------------

# ================================================================================================
# PARTE 11: MODELO ESPECIALISTA - ÁRBOL TEXTO POR CLASE (CORREGIDO)
# ================================================================================================

# CORRECCIÓN: Convertir target_classes a lista de manera segura
class_names = list(target_classes) if not isinstance(target_classes, list) else target_classes

# CORRECCIÓN CRÍTICA: Usar X_scaled.columns en lugar de X.columns
feature_names = X_scaled.columns.tolist()

# --- Árbol interno ---
tree_          = modelo_generalizado.tree_
n_nodes        = tree_.node_count
children_left  = tree_.children_left
children_right = tree_.children_right
features_idx   = tree_.feature
thresholds     = tree_.threshold

# CORRECCIÓN: Manejar shape de values
if tree_.value.ndim == 3:
    values_raw = tree_.value.squeeze(1)  # [n_nodes, n_classes]
else:
    values_raw = tree_.value

n_node_samples = tree_.n_node_samples

# CORRECCIÓN: Detectar nodos hoja de manera compatible
is_leaf = (children_left == -1) & (children_right == -1)

# --- Utilidades ---
def fmt(x, k=2):  # formato con k decimales
    return f"{x:.{k}f}"

def pretty_value_counts(v_float):
    """value como conteos enteros redondeados por clase (evita truncado a 0)."""
    v_int = np.rint(np.asarray(v_float, dtype=float)).astype(int)
    return "[" + ", ".join(str(int(x)) for x in v_int) + "]"

def ascii_tree_por_clase(cname_objetivo, prec=2, idioma="es"):

    target_idx = class_names.index(cname_objetivo)

    # CORRECCIÓN: Usar X_scaled para consistencia
    N_total = float(len(X_scaled))

    # 1) marcar nodos que contienen hojas de la clase objetivo
    has_target = np.zeros(n_nodes, dtype=bool)
    def marcar(u):
        if is_leaf[u]:
            has_target[u] = (values_raw[u].argmax() == target_idx)
            return has_target[u]
        lt = marcar(children_left[u])
        rt = marcar(children_right[u])
        has_target[u] = lt or rt
        return has_target[u]
    marcar(0)

    # 2) recorrer y construir el ASCII solo con ramas relevantes
    lines = []
    def volcar(u, depth):
        indent = "|   " * depth
        if is_leaf[u]:
            v = values_raw[u].astype(float)
            total_leaf = v.sum()
            conf_pct = 100.0 * (v[target_idx] / total_leaf) if total_leaf > 0 else 0.0
            samples_leaf = float(n_node_samples[u])
            supp_pct = 100.0 * (samples_leaf / N_total) if N_total > 0 else 0.0

            c_pred = class_names[int(v.argmax())]
            n      = int(np.rint(n_node_samples[u]))
            value_str = pretty_value_counts(v)

            if idioma == "es":
                line = (f"{indent}|--- class: {c_pred} "
                        f"(samples={n}, value={value_str}, soporte={fmt(supp_pct, prec)}%, "
                        f"confianza={fmt(conf_pct, prec)}%)")
            else:
                line = (f"{indent}|--- class: {c_pred} "
                        f"(samples={n}, value={value_str}, support={fmt(supp_pct, prec)}%, "
                        f"confidence={fmt(conf_pct, prec)}%)")
            lines.append(line)
            return

        # CORRECCIÓN: Verificar índice de característica
        feat_idx = features_idx[u]
        if feat_idx < 0 or feat_idx >= len(feature_names):
            feat_name = f"Feature_{feat_idx}"
        else:
            feat_name = feature_names[feat_idx]

        thr  = thresholds[u]
        if has_target[children_left[u]]:
            lines.append(f"{indent}|--- {feat_name} <= {fmt(thr, prec)}")
            volcar(children_left[u], depth+1)
        if has_target[children_right[u]]:
            lines.append(f"{indent}|--- {feat_name} > {fmt(thr, prec)}")
            volcar(children_right[u], depth+1)

    volcar(0, 0)
    return "\n".join(lines)

# ===============================================
# Ejecutar por clase y guardar .txt (español, %)
# ===============================================
PRECISION_DEC = 2   # decimales para umbrales y porcentajes
IDIOMA = "es"       # 'es' o 'en'

print(" Generando árboles de texto especialistas por clase...")

for cname in class_names:
    header = f"=== Árbol en modo texto — Clase objetivo: {cname} ==="
    print("\n" + "="*75)
    print(header)
    print("="*75)

    try:
        ascii_txt = ascii_tree_por_clase(cname, prec=PRECISION_DEC, idioma=IDIOMA)
        print(ascii_txt)

        fname = f"arbol_texto_por_clase_{cname.lower().replace(' ','_').replace('>','gt').replace('<','lt')}.txt"
        with open(fname, "w", encoding="utf-8") as f:
            f.write(header + "\n\n")
            f.write(ascii_txt + "\n")
        print(f"✓ Guardado: {fname}")

    except Exception as e:
        print(f" Error generando árbol para clase {cname}: {e}")
        continue

print("\n Proceso de generación de árboles de texto completado")

#--------------MODELO ESPECIALISTA-REGLAS-------------------------------

# ================================================================================================
# PARTE 12: MODELO ESPECIALISTA - ÁRBOL TEXTO POR CLASE-FORMATO COMPACTO (CORREGIDO)
# ================================================================================================

print(" Generando resumen compacto de reglas por clase...")

# Cargar las reglas ya generadas exitosamente
reglas_df = pd.read_csv("reglas_modelo_generalizado.csv")

print("\n" + "="*80)
print("RESUMEN DE REGLAS POR CLASE (FORMATO COMPACTO)")
print("="*80)

# Obtener las clases únicas del DataFrame de reglas
class_names = reglas_df['class'].unique()

for cname in class_names:
    reglas_clase = reglas_df[reglas_df['class'] == cname]
    print(f"\nClase: {cname} — {len(reglas_clase)} regla(s)")

    # Mostrar solo las primeras 10 reglas para no saturar la salida
    for i, (_, regla) in enumerate(reglas_clase.head(10).iterrows(), 1):
        conds_str = regla['conditions'] if regla['conditions'] else "(siempre)"
        print(f"  {i}) IF {conds_str} THEN class = {cname}")

    # Si hay más de 10 reglas, mostrar resumen
    if len(reglas_clase) > 10:
        print(f"  ... y {len(reglas_clase) - 10} reglas más")

# --- ANÁLISIS DETALLADO POR CLASE ---
print("\n" + "="*80)
print("ANÁLISIS DETALLADO POR CLASE")
print("="*80)

for cname in class_names:
    reglas_clase = reglas_df[reglas_df['class'] == cname]

    print(f"\n CLASE: {cname}")
    print(f"   Total de reglas: {len(reglas_clase)}")
    print(f"   Confianza promedio: {reglas_clase['confidence_%'].mean():.1f}%")
    print(f"   Soporte promedio: {reglas_clase['support_%'].mean():.3f}%")

    # Reglas más confiables
    top_confianza = reglas_clase.nlargest(3, 'confidence_%')
    if len(top_confianza) > 0:
        print(f"   Regla más confiable: {top_confianza['confidence_%'].iloc[0]:.1f}%")

    # Reglas con mayor soporte
    top_soporte = reglas_clase.nlargest(3, 'support_%')
    if len(top_soporte) > 0:
        print(f"   Regla con mayor soporte: {top_soporte['support_%'].iloc[0]:.3f}%")

# Guardar resumen compacto
with open("resumen_reglas_por_clase_compacto.txt", "w", encoding="utf-8") as f:
    f.write("RESUMEN DE REGLAS POR CLASE (FORMATO COMPACTO)\n")
    f.write("="*80 + "\n\n")

    for cname in class_names:
        reglas_clase = reglas_df[reglas_df['class'] == cname]
        f.write(f"Clase: {cname} — {len(reglas_clase)} regla(s)\n")
        f.write(f"Confianza promedio: {reglas_clase['confidence_%'].mean():.1f}%\n")
        f.write(f"Soporte promedio: {reglas_clase['support_%'].mean():.3f}%\n\n")

        for i, (_, regla) in enumerate(reglas_clase.iterrows(), 1):
            conds_str = regla['conditions'] if regla['conditions'] else "(siempre)"
            f.write(f"{i:3d}) IF {conds_str} THEN class = {cname}\n")
            f.write(f"     (soporte: {regla['support_%']}%, confianza: {regla['confidence_%']}%)\n\n")

print("✓ Guardado: resumen_reglas_por_clase_compacto.txt")

# --- RESUMEN EJECUTIVO ---
print("\n" + "="*80)
print("RESUMEN EJECUTIVO - DISTRIBUCIÓN DE REGLAS")
print("="*80)

total_reglas = len(reglas_df)
print(f" Total de reglas en el modelo: {total_reglas}")

for cname in class_names:
    reglas_clase = reglas_df[reglas_df['class'] == cname]
    porcentaje = (len(reglas_clase) / total_reglas) * 100
    print(f"   {cname}: {len(reglas_clase)} reglas ({porcentaje:.1f}%)")

# --- EXPORTAR REGLAS POR CLASE EN ARCHIVOS SEPARADOS ---
print("\n" + "="*80)
print("EXPORTANDO REGLAS POR CLASE EN ARCHIVOS SEPARADOS")
print("="*80)

for cname in class_names:
    reglas_clase = reglas_df[reglas_df['class'] == cname]

    # Crear nombre de archivo seguro
    safe_name = str(cname).lower().replace(' ', '_').replace('>', 'gt').replace('<', 'lt')
    filename = f"reglas_especializadas_clase_{safe_name}.csv"

    # Ordenar por confianza descendente
    reglas_clase = reglas_clase.sort_values('confidence_%', ascending=False)
    reglas_clase.to_csv(filename, index=False, encoding="utf-8")
    print(f"✓ {cname}: {len(reglas_clase)} reglas guardadas en {filename}")

print("\n PROCESO COMPLETADO: Resumen compacto generado exitosamente")

#-------------CODIGO A PREVIO-----------------------
#PARTE 13: "CÓDIGO A BÁSICO"

# ================================================================================================
# PARTE 13: ÁRBOLES ESPECIALISTAS COMPACTADOS CON MONOTONÍA ESTRICTA (PODA)
#           - Se usa máscara estricta
#           - Se compactan desigualdades padre–hijo de la MISMA variable
#           - Sólo se podan caminos que rompen p_hijo ≥ p_padre
# ================================================================================================

# -----------------------------------------------
# CONFIGURACIÓN BÁSICA (MISMA BD)
# -----------------------------------------------
class_names   = ['Dropout', 'Graduate', 'Enrolled']
feature_names = X_scaled.columns.tolist()

PALETTE = [
    "#FF8C00", "#32CD32", "#8A2BE2", "#00BFFF",
    "#FFD700", "#DA70D6", "#40E0D0", "#FFB6C1",
    "#B0E2FF", "#7FFFD4"
]
CLASS_COLORS = {cls: PALETTE[i % len(PALETTE)] for i, cls in enumerate(class_names)}

# -----------------------------------------------
# FUNCIONES BASE
# -----------------------------------------------
def _arr_str_int(a):
    a = list(map(int, a))
    return "[" + ", ".join(str(x) for x in a) + "]"

def _is_leaf(tree_, u: int) -> bool:
    return tree_.children_left[u] == -1

def _predicted_class_idx(tree_, u: int) -> int:
    """
    Índice de la clase predicha en el nodo u.
    Funciona tanto si value tiene forma (n_nodes, n_classes)
    como (n_nodes, 1, n_classes).
    """
    v = np.asarray(tree_.value[u], dtype=float)
    v = v.reshape(-1)        # vector 1D de tamaño n_clases
    return int(np.argmax(v))


def _node_prob_for_class(tree_, u: int, class_idx: int) -> float:
    """
    Probabilidad de la clase 'class_idx' en el nodo u.
    Compatibles con tree_.value de cualquier forma estándar.
    """
    v = np.asarray(tree_.value[u], dtype=float)
    v = v.reshape(-1)        # [n_clases]
    s = v.sum()
    if s <= 0:
        return 0.0
    return float(v[class_idx] / s)


def _node_counts_and_probvec(tree_, u: int):
    """
    Devuelve:
       - w: vector 1D con los conteos por clase
       - probs: vector 1D con las probabilidades por clase
       - samples: número total de muestras en el nodo
    """
    v = np.asarray(tree_.value[u], dtype=float)
    w = v.reshape(-1)        # [n_clases]
    s = w.sum()
    if s > 0:
        probs = w / s
    else:
        probs = np.zeros_like(w)
    samples = int(tree_.n_node_samples[u])
    return w, probs, samples


def _max_leaf_prob_for_class_with_support(tree_, class_idx: int, min_samples: int) -> float:
    maxp = 0.0
    for u in range(tree_.node_count):
        if _is_leaf(tree_, u) and _predicted_class_idx(tree_, u) == class_idx:
            if int(tree_.n_node_samples[u]) >= int(min_samples):
                p = _node_prob_for_class(tree_, u, class_idx)
                if p > maxp:
                    maxp = p
    return maxp

# ================================================================================================
# MÁSCARA MONOTÓNICA ESTRICTA (PODA), BASADA EN PARTE 14
# ================================================================================================
def _keep_mask_strict_monotonic(tree_, class_idx, tau, min_samples_to_keep: int = 0):
    """
    Mantiene SOLO caminos donde la probabilidad de la clase es NO DECRECIENTE:
        p_hijo >= p_padre en cada paso.

    Además, la hoja:
        - predice la clase objetivo,
        - tiene p >= tau,
        - tiene soporte >= min_samples_to_keep.

    Cualquier rama que viole p_hijo < p_padre se poda completamente.
    """
    n = tree_.node_count
    keep = np.zeros(n, dtype=bool)

    def dfs(u: int, parent_p: float = 0.0) -> bool:
        samples_u = int(tree_.n_node_samples[u])
        p_current = _node_prob_for_class(tree_, u, class_idx)

        # Poda inmediata si viola monotonía local
        if p_current < parent_p:
            return False

        if _is_leaf(tree_, u):
            ok = (
                _predicted_class_idx(tree_, u) == class_idx and
                p_current >= tau and
                samples_u >= min_samples_to_keep
            )
            if ok:
                keep[u] = True
            return ok

        L, R = int(tree_.children_left[u]), int(tree_.children_right[u])
        left_ok  = dfs(L, p_current)
        right_ok = dfs(R, p_current)

        if left_ok or right_ok:
            keep[u] = True
            return True

        # Este nodo no conduce a hojas válidas
        return False

    dfs(0, 0.0)
    return keep

# ================================================================================================
# CAMINOS RAÍZ→HOJA Y COMPACTACIÓN DE DESIGUALDADES
# ================================================================================================
def _get_paths_for_class(tree_, keep):
    """
    Devuelve dict: leaf_id -> lista de (feat_idx, thr, op, node_id)
    op = '<=' si vamos por la izquierda (True), '>' si vamos por la derecha (False).
    Solo recorre nodos con keep=True.
    """
    paths = {}

    def dfs(u, path):
        if not keep[u]:
            return

        if _is_leaf(tree_, u):
            paths[u] = list(path)
            return

        feat_idx = int(tree_.feature[u])
        thr = float(tree_.threshold[u])
        L = int(tree_.children_left[u])
        R = int(tree_.children_right[u])

        # Izquierda: condición feat <= thr
        if keep[L]:
            dfs(L, path + [(feat_idx, thr, "<=", u)])
        # Derecha: condición feat > thr
        if keep[R]:
            dfs(R, path + [(feat_idx, thr, ">", u)])

    dfs(0, [])
    return paths

def _compact_path_to_intervals(path):
    """
    path: lista de (feat_idx, thr, op, node_id) en orden de recorrido real.
    Compacta, por feature, la intersección de todas sus desigualdades en el camino.

    IMPORTANTE PARA MONOTONÍA:
      - El nodo "representativo" de cada feature será el de PRIMERA aparición
        (mismas estadísticas que el árbol original en ese punto).
      - El orden de las condiciones en el árbol compacto respeta ese orden
        de primera aparición (subsecuencia de un camino real, que ya es monótono).

    Devuelve lista de dicts:
        {"text": "<condición compacta>",
         "node_idx": índice de nodo representativo}
    """
    import math

    bounds = {}   # feat_name -> {lower, upper, node_idx, first_pos}
    pos = 0

    for feat_idx, thr, op, node_id in path:
        if feat_idx < 0:
            pos += 1
            continue

        feat_name = feature_names[feat_idx]

        if feat_name not in bounds:
            # Primera vez que vemos esta feature → fijamos nodo representativo aquí
            bounds[feat_name] = {
                "lower": -math.inf,
                "upper":  math.inf,
                "node_idx": node_id,     # <-- nodo de PRIMERA aparición
                "first_pos": pos
            }

        b = bounds[feat_name]

        # Actualizar intervalo (intersección de desigualdades)
        if op == "<=":
            b["upper"] = min(b["upper"], thr)
        else:  # '>'
            b["lower"] = max(b["lower"], thr)

        pos += 1

    # Construir lista en el orden de primera aparición en el camino
    conds = []
    for feat_name in sorted(bounds.keys(), key=lambda f: bounds[f]["first_pos"]):
        b = bounds[feat_name]
        lo, hi, node_idx = b["lower"], b["upper"], b["node_idx"]

        if lo == -math.inf and hi == math.inf:
            continue
        elif lo == -math.inf:
            text = f"{feat_name} <= {hi:.3f}"
        elif hi == math.inf:
            text = f"{feat_name} > {lo:.3f}"
        else:
            text = f"{lo:.3f} < {feat_name} <= {hi:.3f}"

        conds.append({"text": text, "node_idx": node_idx})

    return conds

# ================================================================================================
# ÁRBOL VIRTUAL COMPACTADO + PODA ESTRICTA EN LA VISUALIZACIÓN
# ================================================================================================
def build_compacted_graphviz_strict(modelo, clase, tau, soporte, keep, dpi=220):
    """
    Árbol COMPACTADO ESPECIALISTA para una clase:

    1) Usa máscara estricta _keep_mask_strict_monotonic → solo caminos con p_hijo ≥ p_padre.
    2) En cada camino, compacta desigualdades por feature en UNA condición.
    3) Construye árbol virtual donde cada nodo interno tiene:
           - condición compacta,
           - métricas del nodo real (PRIMERA aparición de la feature).
    4) En el árbol virtual volvemos a aplicar poda local:
           solo dibujamos aristas donde p_hijo >= p_padre.
       (por si la compartición de nodos entre caminos generara violaciones).

    Se omiten nodos/reglas que rompeln la reglas.
    """
    import graphviz
    from IPython.display import Image as IPImage, display

    tree_ = modelo.tree_
    cidx = class_names.index(clase)
    color_clase = CLASS_COLORS.get(clase, "#FFFFFF")

    # --- 1) caminos raíz→hoja válidos, ya filtrados por monotonía estricta ---
    paths = _get_paths_for_class(tree_, keep)    # leaf -> [(feat,thr,op,node), ...]

    if not paths:
        print(f"  → No hay caminos compactables para la clase {clase}.")
        return None

    # --- 2) compactar condiciones por camino ---
    compacted_paths = {}                         # leaf -> [ {text, node_idx}, ... ]
    for leaf, path in paths.items():
        compacted_paths[leaf] = _compact_path_to_intervals(path)

    # --- 3) construir árbol virtual: nodos internos y hojas ---
    next_id = 0
    node_children = {}   # node_id -> dict(cond_text -> child_node_id)
    node_label    = {}   # node_id -> texto de condición (para internos)
    node_src_idx  = {}   # node_id -> índice de nodo real representativo
    leaf_by_node  = {}   # node_id -> leaf_idx real asociado

    def new_internal(label_text, src_idx=None):
        nonlocal next_id
        node_id = f"N{next_id}"
        next_id += 1
        node_children[node_id] = {}
        node_label[node_id] = label_text
        node_src_idx[node_id] = src_idx
        return node_id

    # raíz virtual
    root_id = new_internal("ROOT", src_idx=None)

    # Construir la estructura compartida de prefijos compactados
    for leaf_idx, cond_list in compacted_paths.items():
        current = root_id
        for cond_info in cond_list:
            text    = cond_info["text"]
            src_idx = cond_info["node_idx"]

            children = node_children[current]
            if text not in children:
                child_id = new_internal(text, src_idx=src_idx)
                children[text] = child_id
            current = children[text]
        # el nodo interno final corresponde a una hoja real
        leaf_by_node[current] = leaf_idx

    # --- 4) función auxiliar para obtener p(clase) de un nodo real ---
    def prob_of_src(src_idx: int) -> float:
        if src_idx is None or src_idx < 0:
            return 0.0
        return _node_prob_for_class(tree_, src_idx, cidx)

    # --- 5) dibujar con poda estricta en el árbol virtual ---
    dot = graphviz.Digraph(
        graph_attr={
            "rankdir": "TB",
            "dpi": str(dpi),
            "splines": "true",
            "nodesep": "0.35",
            "ranksep": "0.5",
            "fontname": "Helvetica",
            "label": f"Clase: {clase} | τ={tau:.2f} | soporte≥{soporte} | ÁRBOL COMPACTADO (MONOTÓNICO ESTRICTO)",
            "labelloc": "t",
        },
        node_attr={
            "shape": "box",
            "style": "rounded,filled",
            "fontname": "Helvetica",
            "fontsize": "11",
            "penwidth": "1.6",
            "color": "black",
        },
        edge_attr={
            "fontname": "Helvetica",
            "fontsize": "10",
            "color": "black",
            "arrowsize": "0.8",
        },
    )

    # cache de prob de cada nodo virtual
    prob_virtual = {}

    def draw(node_id, parent_p: float = 0.0):
        # Probabilidad en este nodo virtual
        src_idx = node_src_idx.get(node_id, None)
        p_here  = prob_of_src(src_idx) if src_idx is not None else parent_p
        prob_virtual[node_id] = p_here

        # Nodo interno
        if node_id == root_id:
            label = "ROOT"
            dot.node(node_id, label=label, fillcolor=color_clase)
        else:
            base_cond = node_label[node_id]
            if src_idx is not None and src_idx >= 0:
                w, probs, samples = _node_counts_and_probvec(tree_, src_idx)
                gini = float(tree_.impurity[src_idx])
                p_c  = float(probs[cidx]) if probs.size > 0 else 0.0
                est_counts = np.rint(probs * samples).astype(int)
                pred_lbl = class_names[int(np.argmax(w))]
                label = (
                    f"{base_cond}\n"
                    f"gini = {gini:.3f} | samples = {samples}\n"
                    f"p({clase}) = {p_c:.4f}\n"
                    f"class = {pred_lbl}"
                )
            else:
                label = base_cond

            dot.node(node_id, label=label, fillcolor=color_clase)

        # Hijos internos (con poda p_hijo < p_padre)
        for cond_text, child_id in node_children[node_id].items():
            src_child = node_src_idx.get(child_id, None)
            p_child   = prob_of_src(src_child) if src_child is not None else p_here

            if p_child < p_here:
                # Poda virtual: no dibujamos ramas que rompen monotonía
                continue

            dot.edge(node_id, child_id, label="")
            draw(child_id, p_here)

        # Hoja asociada (si existe)
        if node_id in leaf_by_node:
            leaf_idx = leaf_by_node[node_id]
            w_leaf, probs_leaf, samples_leaf = _node_counts_and_probvec(tree_, leaf_idx)
            p_c_leaf = float(probs_leaf[cidx]) if probs_leaf.size > 0 else 0.0
            est_counts_leaf = np.rint(probs_leaf * samples_leaf).astype(int)
            pred_lbl_leaf = class_names[int(np.argmax(w_leaf))]

            # por construcción de la máscara estricta, p_leaf >= p_here
            leaf_label = (
                f"samples = {samples_leaf}\n"
                f"value = {_arr_str_int(est_counts_leaf)}\n"
                f"p({clase}) = {p_c_leaf:.4f}\n"
                f"class = {pred_lbl_leaf}"
            )
            leaf_node_id = f"L{leaf_idx}"
            dot.node(leaf_node_id, label=leaf_label,
                     shape="ellipse", fillcolor=color_clase)
            dot.edge(node_id, leaf_node_id, label="")

    draw(root_id, parent_p=0.0)

    # --- guardar PNG ---
    safe_clase = clase.replace('>', 'MAS').replace('<', 'MENOS').replace(' ', '_')
    fname = f"ARBOL_COMPACTADO_MONO_{safe_clase}"
    path = dot.render(fname, format="png", cleanup=True)
    print(f"✓ Árbol compactado MONÓTONO para {clase} guardado como: {path}")
    display(IPImage(filename=path))
    return path

# ================================================================================================
# TABLA τ MÁXIMO (OPCIONAL, IGUAL QUE ANTES)
# ================================================================================================
print("TABLA DE τ MÁXIMO ALCANZABLE (MONOTONÍA ESTRICTA USADA EN LOS ÁRBOLES)")
print("=" * 70)

tree_ = modelo_generalizado.tree_
soportes = [1, 10, 30, 50]
resultados = {}

for clase in class_names:
    resultados[clase] = []
    cidx = class_names.index(clase)
    for soporte in soportes:
        tau_max = _max_leaf_prob_for_class_with_support(tree_, cidx, soporte)
        resultados[clase].append(tau_max)

df_tau = pd.DataFrame(resultados, index=soportes)
df_tau.index.name = 'Soporte_Mínimo'
print(df_tau.round(3))

# ================================================================================================
# EJECUCIÓN: ÁRBOLES COMPACTADOS MONÓTONOS POR CLASE (PODA ESTRICTA)
# ================================================================================================
print("\n" + "="*80)
print("GENERANDO ÁRBOLES ESPECIALISTAS COMPACTADOS CON MONOTONÍA ESTRICTA")
print("="*80)

# Puedes ajustar τ_inicial y soporte según lo que viste en PARTE 14
configuraciones = [
    ('Dropout', 0.1, 30),      # τ máximo = 1.0, usamos 0.85 con soporte 30
    ('Graduate', 0.85, 30),     # τ máximo = 1.0, usamos 0.85 con soporte 30
    ('Enrolled', 0.7, 10)      # τ máximo = 0.735, usamos 0.7 con soporte 30 (más bajo)
]


for clase, tau_ini, soporte in configuraciones:
    print(f"\nClase: {clase}  | τ_inicial={tau_ini:.2f} | soporte≥{soporte}")
    cidx = class_names.index(clase)

    # τ máximo con ese soporte
    tau_max = _max_leaf_prob_for_class_with_support(tree_, cidx, soporte)
    if tau_max == 0.0:
        print(f"  → No hay hojas para {clase} con soporte≥{soporte}.")
        continue

    tau = min(tau_ini, tau_max)
    if tau_ini > tau_max:
        print(f"  τ_inicial>{tau_max:.3f}, usando τ={tau:.3f}")
    else:
        print(f"  τ={tau:.3f} (máx alcanzable={tau_max:.3f})")

    # MÁSCARA ESTRICTA
    keep = _keep_mask_strict_monotonic(tree_, cidx, tau, min_samples_to_keep=soporte)
    if not keep.any():
        print(f"  → Sin caminos MONÓTONOS válidos para {clase}.")
        continue

    # ÁRBOL COMPACTADO CON PODA ESTRICTA
    build_compacted_graphviz_strict(
        modelo=modelo_generalizado,
        clase=clase,
        tau=tau,
        soporte=soporte,
        keep=keep,
        dpi=220,
    )

print("\n" + "="*80)
print("ANÁLISIS DE ÁRBOLES COMPACTADOS MONÓTONOS COMPLETADO")
print("="*80)

#OE2: Diseñar un algoritmo de explicabilidad por clase para árboles de decisión profundos en problemas multiclase,
#basado en la descomposición de modelos

#y la aplicación de técnicas post-hoc como SHAP,
#utilizando el Patrón de Investigación Iterativa (PII) propuesto por Pratt como marco metodológico,
#para generar explicaciones diferenciadas y comprensibles para cada categoría de la variable objetivo.

# =============================================================================
# PARTE 14 (CORREGIDA): CÁLCULO DE SHAP VALUES CON AJUSTE DE DIMENSIONES
# =============================================================================
import shap

print("\n" + "="*80)
print("PARTE 14: CÁLCULO DE SHAP VALUES (POST-HOC) - VERSIÓN ROBUSTA")
print("="*80)

# 1. Instanciar el explicador
explainer = shap.TreeExplainer(modelo_generalizado)

# 2. Calcular shap_values
# check_additivity=False evita errores numéricos en árboles profundos
try:
    shap_values_raw = explainer.shap_values(X_test, check_additivity=False)
except:
    shap_values_raw = explainer.shap_values(X_test)

# 3. DIAGNÓSTICO Y CORRECCIÓN DE FORMATO
# Convertimos a array numpy para inspeccionar dimensiones
shap_array = np.array(shap_values_raw)
print(f"Dimensiones crudas detectadas: {shap_array.shape}")

# CASO A: Formato (Samples, Features, Classes) -> Típico en nuevas versiones para Multiclase
if len(shap_array.shape) == 3 and shap_array.shape[2] == len(target_classes):
    print("-> Detectado formato (Samples, Features, Classes). Transponiendo...")
    # Transponemos a (Classes, Samples, Features)
    # Axis 0 (Samples) pasa a pos 1
    # Axis 1 (Features) pasa a pos 2
    # Axis 2 (Classes) pasa a pos 0
    shap_values_transposed = shap_array.transpose(2, 0, 1)

    # Convertimos a lista de arrays, que es lo que espera shap.summary_plot
    shap_values = list(shap_values_transposed)

# CASO B: Formato Lista de Arrays (Classes, Samples, Features) -> Formato estándar antiguo
elif isinstance(shap_values_raw, list) and len(shap_values_raw) == len(target_classes):
    print("-> Detectado formato estándar (Lista por Clases). No se requieren cambios.")
    shap_values = shap_values_raw

else:
    print("Warning: Formato SHAP no reconocido estándar. Intentando adaptación automática...")
    shap_values = shap_values_raw

# 4. VALIDACIÓN FINAL
print(f"\nEstructura FINAL SHAP para gráficos:")
print(f"Número de elementos (Clases): {len(shap_values)}")
print(f"Dimensiones matriz Clase 0: {shap_values[0].shape} (debe ser Samples x Features)")

# Verificación rápida
expected_features = X_test.shape[1]
expected_samples = X_test.shape[0]

if shap_values[0].shape == (expected_samples, expected_features):
    print("✓ ESTADO: CORRECTO. Listo para Parte 15.")
else:
    print(f"⚠ ESTADO: REVISAR. Se esperaba ({expected_samples}, {expected_features})")

# =============================================================================
# PARTE 15: PERFILES DE EXPLICABILIDAD GLOBAL POR CLASE
# =============================================================================

print("\n" + "="*80)
print("PARTE 15: GENERAR PERFILES SHAP POR CLASE (SUMMARY PLOTS)")
print("="*80)

# Verificación de seguridad antes de graficar
if 'shap_values' not in locals():
    raise ValueError("¡Error! La variable 'shap_values' no existe. Ejecuta la PARTE 14 primero.")

def graficar_shap_por_clase_optimizado(shap_vals_list, X_eval, feat_names, classes):
    """
    Genera y guarda un gráfico de abejas (beeswarm) para cada clase.
    """
    # Asegurar que feature_names sea una lista simple
    if hasattr(feat_names, 'tolist'):
        feat_names = feat_names.tolist()

    for i, class_name in enumerate(classes):
        print(f"Generando perfil para clase {i}: {class_name}...")

        plt.figure(figsize=(12, 8))
        plt.title(f"Impacto de variables en probabilidad de: {class_name}", fontsize=14)

        # shap_vals_list[i] es la matriz (Samples, Features) para la clase i
        # X_eval provee los valores reales de las características (para el color rojo/azul)
        shap.summary_plot(
            shap_vals_list[i],
            X_eval,
            feature_names=feat_names,
            show=False,
            plot_type="dot",
            max_display=15 # Mostrar top 15 variables
        )

        # Ajuste de diseño
        plt.tight_layout()

        # Guardado seguro
        safe_name = str(class_name).replace(' ', '_')
        filename = f"SHAP_GLOBAL_CLASE_{safe_name}.png"
        plt.savefig(filename, dpi=300, bbox_inches='tight')
        plt.close() # Cerrar figura para liberar memoria

        print(f"  ✓ Gráfico guardado: {filename}")

# Ejecutar generación
# Nota: X_test viene de tu PARTE 4 (DataFrame escalado)
graficar_shap_por_clase_optimizado(shap_values, X_test, feature_names, target_classes)

print("\nProceso de visualización global completado.")

# =============================================================================
# PARTE 16: SELECCIÓN ESTRATÉGICA DE PROTOTIPOS (CENTROIDES DE EXPLICACIÓN)
# =============================================================================

print("\n" + "="*80)
print("PARTE 16: BÚSQUEDA DE PROTOTIPOS DE ALTA CONFIANZA")
print("="*80)

def seleccionar_prototipos_robusto(model, X, y_true, classes, map_dict):
    """
    Selecciona la instancia con mayor probabilidad predicha (y acierto correcto)
    para cada clase.
    """
    # 1. Obtener predicciones y probabilidades
    probs = model.predict_proba(X)
    preds = model.predict(X)

    # 2. Normalizar y_true a array numpy para indexación booleana
    if isinstance(y_true, pd.Series):
        y_true_arr = y_true.values
    else:
        y_true_arr = np.array(y_true)

    prototipos = {}

    print(f"Buscando prototipos en {len(X)} instancias de prueba...")

    for class_name in classes:
        # Obtener el índice numérico de la clase usando el mapa (ej: 'Dropout' -> 0)
        if class_name in map_dict:
            idx_class_num = map_dict[class_name]
        else:
            # Fallback si el mapa no coincide exactamente
            print(f"Advertencia: '{class_name}' no encontrado en target_map. Usando índice de lista.")
            idx_class_num = classes.index(class_name)

        # 3. Filtrar: Instancias que SON de esa clase Y fueron PREDICHAS como esa clase
        mask = (y_true_arr == idx_class_num) & (preds == idx_class_num)

        count_matches = np.sum(mask)

        if count_matches > 0:
            # Índices relativos dentro de X_test
            indices_relativos = np.where(mask)[0]

            # Extraer probabilidades solo para esta clase
            probs_de_clase = probs[indices_relativos, idx_class_num]

            # Encontrar el índice del máximo valor
            best_sub_idx = np.argmax(probs_de_clase)

            # Índice real en el array X_test
            idx_final = indices_relativos[best_sub_idx]
            max_prob = probs_de_clase[best_sub_idx]

            prototipos[class_name] = {
                'index_loc': idx_final,       # Índice posicional (0 a N-1) para usar con iloc/numpy
                'prob': max_prob,
                'true_label': class_name,
                'class_idx_int': idx_class_num
            }
            print(f"  ✓ Prototipo {class_name:10s}: Instancia #{idx_final:<4} | Confianza: {max_prob*100:.2f}%")
        else:
            print(f"  ⚠ No se encontraron aciertos correctos para {class_name}")
            prototipos[class_name] = None

    return prototipos

# Ejecución usando las variables que ya tienes cargadas
# target_map viene de tu Parte 2 (ej: {'Dropout':0, ...})
dict_prototipos = seleccionar_prototipos_robusto(modelo_generalizado, X_test, Y_test, target_classes, target_map)

print("\nDiccionario de prototipos generado correctamente.")

# =============================================================================
# PARTE 17: EXPLICACIONES LOCALES (WATERFALL PLOTS)
# =============================================================================

print("\n" + "="*80)
print("PARTE 17: VISUALIZACIÓN LOCAL (WATERFALL) PARA PROTOTIPOS")
print("="*80)

# 1. Crear el objeto Explanation (necesario para plots modernos de SHAP)
# Usamos X_test completo para mantener la estructura de índices
print("Generando objeto explicativo completo (esto puede tardar unos segundos)...")
explainer_obj = shap.TreeExplainer(modelo_generalizado)
shap_explanation = explainer_obj(X_test) # Devuelve objeto Explanation (N, Feat, Classes)

# 2. Generar plots para cada prototipo
for class_name, info in dict_prototipos.items():
    if info is None:
        continue

    # Extraer datos del diccionario
    idx_test = info['index_loc']
    prob = info['prob']
    class_idx_int = info['class_idx_int'] # Índice numérico de la clase (0, 1 o 2)

    print(f"Generando Waterfall para {class_name} (Instancia {idx_test})...")

    # 3. Extraer el slice específico: [Instancia, Todas las Features, Clase Específica]
    # La estructura de shap_explanation.values es (n_samples, n_features, n_classes)
    explanation_slice = shap_explanation[idx_test, :, class_idx_int]

    # 4. Configurar gráfico
    plt.figure(figsize=(10, 6))

    # shap.plots.waterfall dibuja sobre la figura actual
    # show=False permite seguir modificando (títulos, guardar)
    shap.plots.waterfall(explanation_slice, max_display=12, show=False)

    # Personalización
    plt.title(f"¿Por qué {class_name}? (Probabilidad: {prob:.2%})\nInstancia #{idx_test}", fontsize=12)

    # Guardar
    safe_name = str(class_name).replace(' ', '_')
    filename = f"SHAP_WATERFALL_{safe_name}_IDX{idx_test}.png"
    plt.savefig(filename, bbox_inches='tight', dpi=300)
    plt.close()

    print(f"  ✓ Gráfico guardado: {filename}")

print("\nVisualización local completada.")

# =============================================================================
# PARTE 18: EVALUACIÓN DE CONSISTENCIA (JACCARD INDEX)
# Objetivo: Medir qué tanto coinciden las reglas del árbol con la importancia SHAP.
# =============================================================================


print("\n" + "="*80)
print("PARTE 18: ANÁLISIS DE CONSISTENCIA (REGLAS ESTRUCTURALES VS. SHAP)")
print("="*80)

def calcular_consistencia_jaccard(shap_vals_list, feature_list, class_list, k=5):
    """
    Compara las Top-K características más importantes según SHAP (Global)
    vs. las Top-K características más usadas en las Reglas del Árbol Especialista.
    """
    resultados = []

    # Asegurar que feature_list sea lista
    if hasattr(feature_list, 'tolist'):
        feature_list = feature_list.tolist()

    for i, class_name in enumerate(class_list):
        print(f"Analizando consistencia para clase: {class_name}...")

        # --- A) Top-K Features según SHAP (Promedio Absoluto Global) ---
        # shap_vals_list[i] es la matriz (Samples, Features)
        mean_abs_shap = np.mean(np.abs(shap_vals_list[i]), axis=0)

        # Obtener índices de los mayores valores
        top_indices_shap = np.argsort(mean_abs_shap)[::-1][:k]
        top_k_feats_shap = set([feature_list[idx] for idx in top_indices_shap])

        # --- B) Top-K Features según Reglas del Árbol (Extraído de los CSVs Parte 12) ---
        # Reconstruir nombre del archivo tal como se guardó en Parte 12
        safe_name = str(class_name).lower().replace(' ', '_').replace('>', 'gt').replace('<', 'lt')
        filename_csv = f"reglas_especializadas_clase_{safe_name}.csv"

        top_k_feats_tree = set()
        try:
            df_rules = pd.read_csv(filename_csv)

            # Estrategia: Tomar las features que aparecen en las reglas de mayor confianza
            # Tomamos las top 20 reglas para tener suficiente corpus
            top_rules = df_rules.head(20)

            # Conteo simple de frecuencia de features en las condiciones
            feat_counter = {}
            for cond_str in top_rules['conditions']:
                if pd.isna(cond_str): continue
                for feat in feature_list:
                    # Chequeo simple de substring (puede mejorarse con regex si los nombres son complejos)
                    if feat in cond_str:
                        feat_counter[feat] = feat_counter.get(feat, 0) + 1

            # Ordenar por frecuencia de aparición
            sorted_feats_tree = sorted(feat_counter, key=feat_counter.get, reverse=True)[:k]
            top_k_feats_tree = set(sorted_feats_tree)

        except FileNotFoundError:
            print(f"  ⚠ Advertencia: No se encontró {filename_csv}. Saltando comparación árbol.")

        # --- C) Cálculo de métricas ---
        intersection = top_k_feats_shap.intersection(top_k_feats_tree)
        union = top_k_feats_shap.union(top_k_feats_tree)

        jaccard = len(intersection) / len(union) if len(union) > 0 else 0.0

        resultados.append({
            "Clase": class_name,
            "Jaccard_Index": round(jaccard, 4),
            "Coincidencias": len(intersection),
            "Features_Comunes": list(intersection),
            "Solo_SHAP": list(top_k_feats_shap - top_k_feats_tree),
            "Solo_Arbol": list(top_k_feats_tree - top_k_feats_shap)
        })

    return pd.DataFrame(resultados)

# Ejecutar análisis
df_consistencia = calcular_consistencia_jaccard(shap_values, feature_names, target_classes, k=7)

print("\n--- REPORTE DE CONSISTENCIA XAI (Top 7 Features) ---")
# Mostrar tabla bonita
print(df_consistencia[['Clase', 'Jaccard_Index', 'Coincidencias', 'Features_Comunes']].to_markdown(index=False))

# Guardar reporte completo
df_consistencia.to_csv("REPORTE_FINAL_CONSISTENCIA_XAI.csv", index=False)
print("\n✓ Reporte guardado: REPORTE_FINAL_CONSISTENCIA_XAI.csv")

#OE3 (Por realizar): Evaluar la efectividad de la estrategia de explicabilidad por clase propuesta, comparando la interpretabilidad de las explicaciones generadas
#(mediante métricas cuantitativas como fidelidad y estabilidad,

#así como cualitativas a través de un panel de expertos) frente a las explicaciones obtenidas de enfoques globales del estado del arte,
#con el fin de determinar la mejora en la comprensión y la utilidad para usuarios finales.

#ESTABILIDAD
#Objetivo: Medir si la explicación cambia cuando los datos tienen pequeñas perturbaciones (ruido).
#Resultado esperado: Un valor entre 0 y 1. Más alto es mejor (significa que la explicación es estable y confiable).

# =============================================================================
# PARTE 19: EVALUACIÓN DE ESTABILIDAD (OE3)
# Métrica: Jaccard promedio de Top-K Features al añadir ruido.
# =============================================================================

print("\n" + "="*80)
print("PARTE 19: EVALUACIÓN DE ESTABILIDAD (STABILITY)")
print("="*80)

def evaluar_estabilidad(model, X, feature_names, noise_level=0.05, k=5, n_samples=50):
    # 1. Muestra aleatoria
    if len(X) > n_samples:
        indices_sample = np.random.choice(len(X), n_samples, replace=False)
        X_sample = X.iloc[indices_sample].copy()
    else:
        X_sample = X.copy()

    print(f"Evaluando estabilidad en muestra de {len(X_sample)} instancias...")

    # 2. SHAP Original
    explainer = shap.TreeExplainer(model)
    try:
        shap_orig_raw = explainer.shap_values(X_sample, check_additivity=False)
    except:
        shap_orig_raw = explainer.shap_values(X_sample)

    # Estandarizar a lista
    if not isinstance(shap_orig_raw, list):
        if len(np.array(shap_orig_raw).shape) == 3:
            shap_orig = [np.array(shap_orig_raw)[:, :, i] for i in range(np.array(shap_orig_raw).shape[2])]
        else:
            shap_orig = [np.array(shap_orig_raw)] # Caso binario simple
    else:
        shap_orig = shap_orig_raw

    # 3. Generar Ruido
    X_noisy = X_sample.copy()
    # Solo añadir ruido a columnas numéricas para evitar errores
    cols_numericas = X_noisy.select_dtypes(include=[np.number]).columns
    for col in cols_numericas:
        std = X_noisy[col].std()
        if std == 0: std = 0.01 # Evitar error en constantes
        noise = np.random.normal(0, std * noise_level, size=len(X_noisy))
        X_noisy[col] += noise

    # 4. SHAP Perturbado
    try:
        shap_pert_raw = explainer.shap_values(X_noisy, check_additivity=False)
    except:
        shap_pert_raw = explainer.shap_values(X_noisy)

    if not isinstance(shap_pert_raw, list):
        if len(np.array(shap_pert_raw).shape) == 3:
            shap_pert = [np.array(shap_pert_raw)[:, :, i] for i in range(np.array(shap_pert_raw).shape[2])]
        else:
            shap_pert = [np.array(shap_pert_raw)]
    else:
        shap_pert = shap_pert_raw

    # 5. Calcular Jaccard
    stability_scores = {}
    num_clases = len(shap_orig)

    for c in range(num_clases):
        jaccards = []
        for i in range(len(X_sample)):
            # Top K Original
            vals_orig = np.abs(shap_orig[c][i])
            top_idx_orig = set(np.argsort(vals_orig)[::-1][:k])

            # Top K Perturbado
            vals_pert = np.abs(shap_pert[c][i])
            top_idx_pert = set(np.argsort(vals_pert)[::-1][:k])

            inter = len(top_idx_orig.intersection(top_idx_pert))
            union = len(top_idx_orig.union(top_idx_pert))
            jaccard = inter / union if union > 0 else 0
            jaccards.append(jaccard)

        stability_scores[c] = np.mean(jaccards)

    return stability_scores

# EJECUCIÓN
estabilidad_res = evaluar_estabilidad(modelo_generalizado, X_test, feature_names, n_samples=100)

print("\n--- RESULTADOS DE ESTABILIDAD (Promedio Jaccard) ---")
# Intento de recuperar nombres bonitos si existen mapas previos
nombres_mapa = None
# Buscamos variables comunes de mapas de las BDs anteriores
if 'mapa_nombres_bd4' in globals(): nombres_mapa = mapa_nombres_bd4
elif 'mapa_nombres_bd5' in globals(): nombres_mapa = mapa_nombres_bd5
elif 'mapa_nombres_bd6' in globals(): nombres_mapa = mapa_nombres_bd6
elif 'mapa_nombres_bd7' in globals(): nombres_mapa = mapa_nombres_bd7
elif 'mapa_nombres_bd3' in globals(): nombres_mapa = mapa_nombres_bd3
elif 'target_map' in globals() and isinstance(list(target_map.keys())[0], str):
    # Invertir target_map si es {Nombre: Int}
    nombres_mapa = {v: k for k, v in target_map.items()}

lista_res = []
for cls_idx, score in estabilidad_res.items():
    nombre = str(cls_idx)
    if nombres_mapa: nombre = nombres_mapa.get(cls_idx, str(cls_idx))
    elif isinstance(target_classes[0], str) and cls_idx < len(target_classes):
        nombre = target_classes[cls_idx] # Usar target_classes si son strings

    print(f"  Clase '{nombre}': {score:.4f}")
    lista_res.append({'Clase': nombre, 'Estabilidad': score})

# Guardar
pd.DataFrame(lista_res).to_csv("METRICAS_ESTABILIDAD_OE3.csv", index=False)
print("\n✓ Guardado: METRICAS_ESTABILIDAD_OE3.csv")

#FIDELIDAD
#Objetivo: Medir qué tan bien un árbol simple (la explicación) imita al modelo complejo.
#Resultado esperado: Un Accuracy (0 a 1). Un valor > 0.75 indica que se puede confiar en la explicación simple.

# =============================================================================
# PARTE 20: EVALUACIÓN DE FIDELIDAD (FIDELITY) - OE3
# Método: Surrogate Tree Accuracy (Árbol Simple vs. Modelo Complejo)
# =============================================================================

print("\n" + "="*80)
print("PARTE 20: EVALUACIÓN DE FIDELIDAD (FIDELITY)")
print("="*80)

def evaluar_fidelidad_surrogate(model_complex, X, y_pred_complex, classes):
    fidelity_scores = {}

    for i, class_val in enumerate(classes):
        # Target binario: ¿El modelo complejo predijo esta clase? (1 o 0)
        # Si classes son strings, asumimos que y_pred son ints (indices)
        if isinstance(class_val, str):
             target_binary = (y_pred_complex == i).astype(int)
        else:
             target_binary = (y_pred_complex == class_val).astype(int)

        # Si solo hay una clase (ej. nunca predijo '4'), fidelidad es trivial 1.0
        if len(np.unique(target_binary)) < 2:
            fidelity_scores[i] = 1.0
            continue

        # Entrenar Árbol Sustituto (Explicable, profundidad 3)
        surrogate = DecisionTreeClassifier(max_depth=3, random_state=42)
        surrogate.fit(X, target_binary)

        # Comparar predicciones
        surrogate_preds = surrogate.predict(X)
        fidelity = accuracy_score(target_binary, surrogate_preds)
        fidelity_scores[i] = fidelity

    return fidelity_scores

# 1. Obtener predicciones del modelo complejo
y_pred_deep = modelo_generalizado.predict(X_test)

# 2. Calcular
fidelidad_res = evaluar_fidelidad_surrogate(modelo_generalizado, X_test, y_pred_deep, target_classes)

print("\n--- RESULTADOS DE FIDELIDAD (Accuracy Sustituto) ---")
lista_fid = []

# Reutilizamos la lógica de nombres del bloque anterior
for cls_idx, score in fidelidad_res.items():
    nombre = str(cls_idx)
    if nombres_mapa: nombre = nombres_mapa.get(cls_idx, str(cls_idx))
    elif isinstance(target_classes[0], str) and cls_idx < len(target_classes):
        nombre = target_classes[cls_idx]

    print(f"  Clase '{nombre}': {score:.4f}")
    lista_fid.append({'Clase': nombre, 'Fidelidad': score})

# Guardar
pd.DataFrame(lista_fid).to_csv("METRICAS_FIDELIDAD_OE3.csv", index=False)
print("\n✓ Guardado: METRICAS_FIDELIDAD_OE3.csv")
print("\n¡CÓDIGO COMPLETADO! Métricas OE3 generadas.")

#REDUCCIÓN COMPLEJIDAD
#Objetivo: Medir la reducción de carga cognitiva comparando la profundidad máxima del árbol global (peor caso) vs. la longitud promedio del especialista.
#Resultado esperado: Reducción positiva (ej. 30% - 40%). Indica cuánto se simplifica la estructura al aislar una clase.

# =============================================================================
# PARTE 21: CÁLCULO DE REDUCCIÓN DE COMPLEJIDAD (MAX vs AVG)
# =============================================================================


print("\n" + "="*80)
print("PARTE 21: REDUCCIÓN DE COMPLEJIDAD COGNITIVA (MAX vs AVG)")
print("="*80)

def calcular_reduccion_complejidad_max(modelo_global, classes, mapa=None):
    """
    Comparar la Profundidad Máxima del árbol global (Complejidad Total)
    con la Profundidad Promedio de las reglas por clase.
    """
    resultados = []
    tree_ = modelo_global.tree_

    # 1. Obtener la Profundidad Máxima del Modelo Global (El "Techo" de complejidad)
    profundidad_max_global = modelo_global.get_depth()
    print(f"Profundidad Máxima del Árbol Global: {profundidad_max_global}")

    # 2. Iterar por cada clase
    for i, class_id in enumerate(classes):
        # Definir nombre
        nombre_real = str(class_id)
        if mapa: nombre_real = mapa.get(class_id, str(class_id))

        longitudes = []

        # Recorrer el árbol para encontrar reglas de esta clase
        stack = [(0, 0)]
        while len(stack) > 0:
            node_id, depth = stack.pop()

            if tree_.children_left[node_id] == -1: # Es hoja
                pred_class = np.argmax(tree_.value[node_id])

                # Ajuste de índice
                target_idx = i

                if pred_class == target_idx:
                    longitudes.append(depth)
            else:
                stack.append((tree_.children_left[node_id], depth + 1))
                stack.append((tree_.children_right[node_id], depth + 1))

        # Calcular promedio del especialista
        profundidad_especialista = np.mean(longitudes) if longitudes else 0
        num_reglas = len(longitudes)

        # 3. Calcular Reducción (%) respecto al MÁXIMO global
        if profundidad_max_global > 0:
            reduccion = (1 - (profundidad_especialista / profundidad_max_global)) * 100
        else:
            reduccion = 0

        resultados.append({
            "Clase": nombre_real,
            "Complejidad_Global_(Max_Depth)": profundidad_max_global,
            "Complejidad_Especialista_(Avg)": round(profundidad_especialista, 2),
            "Reduccion_Cognitiva_%": round(reduccion, 2),
            "Reglas_Extraidas": num_reglas
        })

    return pd.DataFrame(resultados)

# Detectar mapa activo automáticamente
mapa_uso = None
if 'mapa_nombres_bd4' in globals(): mapa_uso = mapa_nombres_bd4
elif 'mapa_nombres_bd5' in globals(): mapa_uso = mapa_nombres_bd5
elif 'mapa_nombres_bd6' in globals(): mapa_uso = mapa_nombres_bd6
elif 'mapa_nombres_bd7' in globals(): mapa_uso = mapa_nombres_bd7
elif 'mapa_nombres_bd3' in globals(): mapa_uso = mapa_nombres_bd3

# Ejecutar
df_complejidad = calcular_reduccion_complejidad_max(modelo_generalizado, target_classes, mapa_uso)

print("\n--- RESULTADOS DE REDUCCIÓN DE COMPLEJIDAD ---")
print(df_complejidad.to_markdown(index=False))
df_complejidad.to_csv("METRICAS_COMPLEJIDAD_COMPARATIVA_OE3.csv", index=False)
print("\n✓ Guardado: METRICAS_COMPLEJIDAD_COMPARATIVA_OE3.csv")

#CORRELACIÓN DE RANGO (RANK CORRELATION)
#Objetivo: Medir si el orden de importancia de las variables es coherente entre la estructura del Árbol (Gini) y la explicación SHAP.
#Resultado esperado: Un coeficiente de Spearman entre -1 y 1.

#> 0.5: Alta coherencia (ambos métodos priorizan las mismas variables).
#< 0.3: Divergencia (el Árbol usa variables que SHAP considera secundarias, o viceversa).

# =============================================================================
# PARTE 22: CONSISTENCIA DE RANKING (RANK CORRELATION - SPEARMAN)
# =============================================================================

print("\n" + "="*80)
print("PARTE 22: CORRELACIÓN DE RANGO (SPEARMAN)")
print("="*80)

def calcular_rank_correlation(modelo, shap_vals_list, classes, mapa=None):
    resultados = []

    # 1. Obtener Importancia Global del Árbol (Criterio Gini/Entropía)
    # Esta es la "opinión" estructural del modelo sobre qué variables importan
    importancia_arbol = modelo.feature_importances_

    for i, class_id in enumerate(classes):
        nombre_real = str(class_id)
        if mapa: nombre_real = mapa.get(class_id, str(class_id))

        # 2. Obtener Importancia SHAP para esta clase
        if isinstance(shap_vals_list, list):
            shap_class = shap_vals_list[i]
        else:
            shap_class = shap_vals_list

        # Promedio absoluto de los valores SHAP (Magnitud de impacto)
        importancia_shap = np.mean(np.abs(shap_class), axis=0)

        # 3. Calcular Correlación de Spearman
        # Compara los rangos (1ro, 2do, 3ro...) no los valores crudos
        corr, p_value = spearmanr(importancia_shap, importancia_arbol)

        resultados.append({
            "Clase": nombre_real,
            "Rank_Correlation": round(corr, 4),
            "Significancia_P": round(p_value, 4)
        })

    return pd.DataFrame(resultados)

# Detectar mapa activo
mapa_uso = None
if 'mapa_nombres_bd4' in globals(): mapa_uso = mapa_nombres_bd4
elif 'mapa_nombres_bd5' in globals(): mapa_uso = mapa_nombres_bd5
elif 'mapa_nombres_bd6' in globals(): mapa_uso = mapa_nombres_bd6
elif 'mapa_nombres_bd7' in globals(): mapa_uso = mapa_nombres_bd7
elif 'mapa_nombres_bd3' in globals(): mapa_uso = mapa_nombres_bd3

# Ejecutar
df_rank = calcular_rank_correlation(modelo_generalizado, shap_values, target_classes, mapa_uso)

print("\n--- RESULTADOS DE RANK CORRELATION ---")
print(df_rank.to_markdown(index=False))
df_rank.to_csv("METRICAS_RANK_CORRELATION_OE3.csv", index=False)
print("\n✓ Guardado: METRICAS_RANK_CORRELATION_OE3.csv")

#COBERTURA (COVERAGE)

#Objetivo: Medir qué porcentaje de las instancias de una clase caen en hojas "puras" o mayoritarias de esa misma clase. Resultado esperado: Un porcentaje (0-100%).
#Resultado esperado:
#Alto: Las reglas especialistas son muy representativas.
#Bajo: La clase está muy fragmentada o mezclada en el árbol (difícil de aislar con reglas simples).

# =============================================================================
# PARTE 23: COBERTURA DE REGLAS (COVERAGE)
# =============================================================================

print("\n" + "="*80)
print("PARTE 23: CÁLCULO DE COBERTURA (COVERAGE)")
print("="*80)

def calcular_coverage(modelo, X_data, y_data, classes, mapa=None):
    resultados = []

    # Obtener en qué hoja cae cada instancia
    leaf_ids = modelo.apply(X_data)
    tree_ = modelo.tree_

    # Asegurar formato numpy para y_data
    y_arr = y_data.values if isinstance(y_data, pd.Series) else y_data

    for i, class_id in enumerate(classes):
        nombre_real = str(class_id)
        if mapa: nombre_real = mapa.get(class_id, str(class_id))

        # 1. Filtrar las instancias que REALMENTE son de esta clase
        if isinstance(class_id, str):
             indices_clase = np.where(y_arr == i)[0]
        else:
             indices_clase = np.where(y_arr == class_id)[0]

        total_instancias = len(indices_clase)

        if total_instancias == 0:
            resultados.append({"Clase": nombre_real, "Cobertura_%": 0.0})
            continue

        # 2. Verificar si cayeron en una hoja que predice su misma clase
        hits = 0
        hojas_instancias = leaf_ids[indices_clase]

        for node_id in hojas_instancias:
            # ¿Qué clase predice esta hoja?
            pred_class_hoja = np.argmax(tree_.value[node_id])

            # Si la hoja predice lo mismo que la clase real, es una cobertura exitosa
            # (La regla especialista funcionó para esta instancia)
            if pred_class_hoja == i:
                hits += 1

        coverage_pct = (hits / total_instancias) * 100

        resultados.append({
            "Clase": nombre_real,
            "Total_Instancias": total_instancias,
            "Instancias_Cubiertas": hits,
            "Cobertura_%": round(coverage_pct, 2)
        })

    return pd.DataFrame(resultados)

# Ejecutar con X_test para medir generalización
df_coverage = calcular_coverage(modelo_generalizado, X_test, Y_test, target_classes, mapa_uso)

print("\n--- RESULTADOS DE COBERTURA ---")
print(df_coverage.to_markdown(index=False))
df_coverage.to_csv("METRICAS_COVERAGE_OE3.csv", index=False)
print("\n✓ Guardado: METRICAS_COVERAGE_OE3.csv")

#-----------------------STREAMLIT------------------------------------

# =============================================================================
# PASO 1: EXPORTAR MODELO Y DATOS PARA STREAMLIT
# Objetivo: Guardar las variables en un archivo .pkl para usarlas en la app web.
# =============================================================================
# =============================================================================
# BLOQUE DE EXPORTACIÓN FINAL (ACTUALIZADO CON Y_TEST)
# Objetivo: Guardar modelo, datos y etiquetas para la App Web.
# =============================================================================
import pickle
import shutil
import os

# 1. ¡CAMBIA ESTE NOMBRE EN CADA NOTEBOOK! (Ej: "BD2_Diabetes", "BD3_Forestal"...)
NOMBRE_BD = "BD1_Educacion"

# 2. Detectar mapa de nombres automáticamente
mapa_a_exportar = None
# Lista de posibles nombres de mapas en tus notebooks
if 'mapa_nombres_bd1' in globals(): mapa_a_exportar = mapa_nombres_bd1
elif 'mapa_nombres_bd2' in globals(): mapa_a_exportar = mapa_nombres_bd2
elif 'mapa_nombres_bd3' in globals(): mapa_a_exportar = mapa_nombres_bd3
elif 'mapa_nombres_bd4' in globals(): mapa_a_exportar = mapa_nombres_bd4
elif 'mapa_nombres_bd5' in globals(): mapa_a_exportar = mapa_nombres_bd5
elif 'mapa_nombres_bd6' in globals(): mapa_a_exportar = mapa_nombres_bd6
elif 'mapa_nombres_bd7' in globals(): mapa_a_exportar = mapa_nombres_bd7
elif 'target_map' in globals() and isinstance(list(target_map.keys())[0], str):
    # Si es el mapa original manual, lo invertimos
    mapa_a_exportar = {v: k for k, v in target_map.items()}

# 3. EMPAQUETAR TODO (INCLUYENDO Y_TEST)
paquete = {
    "nombre_bd": NOMBRE_BD,
    "modelo": modelo_generalizado,
    "feature_names": feature_names,
    "class_names": target_classes,
    "X_test": X_test,
    "y_test": Y_test,                    # <--- ¡ESTO ES LO NUEVO Y NECESARIO!
    "mapa_nombres": mapa_a_exportar
}

# 4. Guardar archivo localmente
nombre_archivo = f"{NOMBRE_BD}_app_data.pkl"
with open(nombre_archivo, "wb") as f:
    pickle.dump(paquete, f)

print(f"Archivo generado: {nombre_archivo}")

# 5. INTENTAR MOVER AUTOMÁTICAMENTE A LA CARPETA DE LA APP
# Ajusta esta ruta si tu carpeta Z_PLATAFORMA_WEB está en otro lado relativo
ruta_destino_carpeta = os.path.join("..", "Z_PLATAFORMA_WEB")

# Si el notebook está en la raíz junto a Z_..., usa esto:
if not os.path.exists(ruta_destino_carpeta):
    ruta_destino_carpeta = "Z_PLATAFORMA_WEB"

ruta_final = os.path.join(ruta_destino_carpeta, nombre_archivo)

try:
    if os.path.exists(ruta_destino_carpeta):
        shutil.copy2(nombre_archivo, ruta_final)
        print(f"Copiado exitosamente a: {ruta_final}")
    else:
        print(f"No encontré la carpeta '{ruta_destino_carpeta}'. Por favor mueve el archivo manualmemte.")
except Exception as e:
    print(f"Error moviendo archivo: {e}. Muévelo manualmente.")

# =============================================================================
# SCRIPT DE RECOLECCIÓN DE ARCHIVOS .PKL
# Objetivo: Buscar archivos de datos en subcarpetas y centralizarlos para la App.
# =============================================================================
import os
import shutil

# 1. Definir rutas (Usamos ruta relativa asumiendo que el notebook está en una subcarpeta)
# ".." significa "ir una carpeta atrás" (a la raíz ARTEXPLIC)
ruta_raiz = ".."
nombre_carpeta_app = "Z_PLATAFORMA_WEB"
ruta_destino = os.path.join(ruta_raiz, nombre_carpeta_app)

print(f"Iniciando búsqueda en: {os.path.abspath(ruta_raiz)}")
print(f"Destino de copiado: {os.path.abspath(ruta_destino)}")

# Verificar si la carpeta destino existe
if not os.path.exists(ruta_destino):
    print(f"⚠️ La carpeta {nombre_carpeta_app} no existe. Por favor crearla en la raíz ARTEXPLIC.")
else:
    # 2. Recorrer carpetas y buscar archivos
    archivos_copiados = 0

    for root, dirs, files in os.walk(ruta_raiz):
        for file in files:
            # Si es un archivo de datos para la app (.pkl)
            if file.endswith("_app_data.pkl"):
                ruta_origen = os.path.join(root, file)
                ruta_final = os.path.join(ruta_destino, file)

                try:
                    shutil.copy2(ruta_origen, ruta_final)
                    print(f"  ✅ Copiado: {file}")
                    archivos_copiados += 1
                except Exception as e:
                    print(f"  ❌ Error al copiar {file}: {e}")

    print(f"\nRESUMEN: Se copiaron {archivos_copiados} archivos a '{nombre_carpeta_app}'.")
    print("Verificar que estén todos tus archivos (BD1 a BD7).")

